server:
  port: 8081
spring:
  application:
    name: gateway-service
  #    name: gateway-limiter
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    password: 1323!Q@#EMSD%$^
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lower-case-service-id: true
      routes:
      - id: service-hi
        uri: lb://SERVICE-HI
        predicates:
        - Path=/demo/**
        filters:
        - StripPrefix=1
#      routes:
#      - id: limit_route
#        uri: http://httpbin.org:80/get
#        predicates:
#        - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#        filters:
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1
#            redis-rate-limiter.burstCapacity: 3
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
