server:
  port: 8081
spring:
  profiles:
    active: after_route

---
spring:
  cloud:
    gateway:
      routes:
        - id: after_route
          uri: https://blog.csdn.net
          filters:
#          - AddRequestHeader=X-Request-Foo, Bar
          - RewritePath=/foo/(?<segment>.*), /$\{segment}
          predicates:
#          AfterRoutePredicateFactory，可配置一个时间，当请求的时间在配置时间之后，才交给 router去处理。否则则报错，不通过路由。
          - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#          Header Route Predicate Factory需要2个参数，一个是header名，另一个header值，该值可以是一个正则表达式。当此断言匹配了请求的header名和值时，断言通过，进入到router的规则中去。
#          - Header=X-Request-Id, \d+
#          Cookie Route Predicate Factory需要2个参数，一个时cookie名字，另一个时值，可以为正则表达式。它用于匹配请求中，带有该名称的cookie和cookie匹配正则表达式的请求。
#          - Cookie=name, forezp
#          Host Route Predicate Factory需要一个参数即hostname，它可以使用. * 等去匹配host。这个参数会匹配请求头中的host的值，一致，则请求正确转发。
#          - Host=**.fangzhipeng.com
#          Method Route Predicate Factory 需要一个参数，即请求的类型。比如GET类型的请求都转发到此路由。在工程的配置文件加上以下的配置：
#          - Method=GET
#          Path Route Predicate Factory 需要一个参数: 一个spel表达式，应用匹配路径。
          - Path=/foo/**
#          Query Route Predicate Factory 需要2个参数:一个参数名和一个参数值的正则表达式
#          - Query=foo, ba.

  profiles: after_route